# Generated by Django 4.0.6 on 2024-01-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service Name')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Service Icon Class')),
            ],
        ),
    ]
