# Generated by Django 4.0.6 on 2024-01-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='description_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='accommodation_images/', verbose_name='Image'),
        ),
    ]
